# -*- coding: utf-8 -*-
"""AdminClass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxaAE9q7ZdzIIgrJvemPCtrXUgMVOjt1
"""

# class Admin(Person):

#   def __init__(self ,name,age,email,username,password,license):
#     super().__init__(name,age,email,username,password,license)

#   def add(self ,id, model , year , price, color , quantity ):
#     for car in available_cars:
#       if car['model'] == model and car['year'] == year and car['color'] == color:
#        return "already exists" 
#     available_cars.append({'id':id , 'model': model , 'year' : year , 'price' : price ,'color': color, 'quantity' : quantity})

#   def delete(self , id):
#     if id not in [car['id'] for car in available_cars]: 
#       print("This car is already deleted or rented.")
#     else: 
#       for car in available_cars : 
#         if car["id"] == id : 
#           available_cars.remove(car)

#   def modify_quantity(self , model , quantity ):
#     if id not in [car['id'] for car in available_cars]:
#       print("This car is already deleted or rented.")
#     else:
#       for car in available_cars:
#         if car['id'] == id:
#           car['quantity'] = quantity

#   def modify_price(self , id , price):
#     if id not in [car['id'] for car in available_cars]:
#       print("This car is already deleted or rented.")
#     else:
#       for car in available_cars:
#         if car['id'] == id:
#           car['price'] = price




available_cars = [ {'id': 1 ,'model' : 'BMW' ,  'year' : 2026 , 'price' : 300 , 'quantity' : 2}]

adm1 = Admin("Wasan" , "wsn41" , "xxxx@gmail.com" , "12345")

adm1.add("Toyota" , 2025 , 120 , 3)


print(cars_available)