# -*- coding: utf-8 -*-
"""AdminClass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxaAE9q7ZdzIIgrJvemPCtrXUgMVOjt1
"""

class Person:
  def __init__(self , name , username , email , password):
    self.name = name
    self.username = username
    self.email = email
    self.__password = password

  def login(self):
    pass

  def display(self):
    print(f"Welcome {self.name} to the Rental Car System!")


class Admin(Person):

  def __init__(self , name , username , email , password):
    super().__init__(name , username , email , password)

  def add(self , model , year , price , quantity ):
    if model not in [car['model'] for car in cars_available]:
      cars_available.append({'model': model , 'year' : year , 'price' : price , 'quantity' : quantity})

  def delete(self , model):
    if model not in [car['model'] for car in cars_available]:
      print("This car is already deleted or rented.")
    else:
      cars_available.remove(
          [car for car in cars_available if car['model'] == model]
      )

  def modify_quantity(self , model , quantity ):
    if model not in [car['model'] for car in cars_available]:
      print("This car is already deleted or rented.")
    else:
      for car in cars_available:
        if car['model'] == model:
          car['quantity'] == quantity

  def modify_price(self , model , price):
    if model not in [car['model'] for car in cars_available]:
      print("This car is already deleted or rented.")
    else:
      for car in cars_available:
        if car['model'] == model:
          car['price'] == price




cars_available = [ {'model' : 'BMW' ,  'year' : 2026 , 'price' : 300 , 'quantity' : 2}]

adm1 = Admin("Wasan" , "wsn41" , "xxxx@gmail.com" , "12345")

adm1.add("Toyota" , 2025 , 120 , 3)


print(cars_available)