# -*- coding: utf-8 -*-
"""Rental_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLRGjk87sYwlQUNOw_XYQoNgvXmqvVnC
"""

# class Person:
#   def __init__(self, username, password, name, email):
#     self.username = username
#     self.password = password
#     self.name = name
#     self.email = email


class Customer(Person):
  def __init__(self,name,age,email,username,password, license,cart):
    super().__init__(name,age,email,username,password,license)
    self.cart = []


  def add_to_cart(self, car, days):

    if len(self.cart) >= 1:
      print("You can only rent one car.")
      return

    rental = car.copy()
    rental["days"] = days

    self.cart.append(rental)

    print("Car added to cart")


  def modify_cart(self, days):

    if not self.cart:
      print("Cart is empty.")
      return

    self.cart[0]["days"] = days

    print("Cart updated")


  def delete_from_cart(self):

    self.cart.clear()

    print("Car removed from cart.")


  def checkout(self):

    if not self.cart:
      print("Cart is empty.")
      return

    car = self.cart[0]

    total = car["price"] * car["days"]

    for available_car in available_cars:
      if available_car["id"] == car["id"]:
        available_car["quantity"] -= 1
        rented_cars.append(car)

        #if no cars are left
        if available_car["quantity"] ==0:
          available_cars.remove(available_car)
          
        break

    self.receipt(total)

    self.cart.clear()


  def receipt(self,total):
    car = self.cart[0]
    return f"Thank you!\n your receipt information: \n car model: {car['model']} \n Year: {car['year']} \n Color: {car['color']} \n Rented days: {car['days']} \n Total price: {total}"

# renter1 = Customer(
#     "aleen123",
#     "1234",
#     "Aleen",
#     "aleen@email.com",
#     22,
#     "123456789"
# )

# renter1.add_to_cart(available_cars[0], 3)

# print(renter1.cart)

