# -*- coding: utf-8 -*-
"""Rental_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLRGjk87sYwlQUNOw_XYQoNgvXmqvVnC
"""

class Person:
  def __init__(self, username, password, name, email):
    self.username = username
    self.password = password
    self.name = name
    self.email = email


class Rental(Person):
  def __init__(self, username, password, name, email, age, license):
    super().__init__(username, password, name, email)
    self.age = age
    self.license = license
    self.cart = []


  def add_to_cart(self, car, days):

    if len(self.cart) >= 1:
      print("You can only rent one car.")
      return

    rental = car.copy()
    rental["days"] = days

    self.cart.append(rental)

    print("Car added to cart")


  def modify_cart(self, days):

    if not self.cart:
      print("Cart is empty.")
      return

    self.cart[0]["days"] = days

    print("Cart updated")


  def delete_from_cart(self):

    self.cart.clear()

    print("Car removed from cart.")


  def checkout(self):

    if not self.cart:
      print("Cart is empty.")
      return

    car = self.cart[0]

    total = car["price"] * car["days"]

    for available_car in available_cars:
      if available_car["id"] == car["id"]:
        available_car["quantity"] -= 1

        #if no cars are left
        if available_car["quantity"] ==0:
          available_cars.remove(available_car)
          unavailable_cars.append(car)

        break

    self.receipt(total)

    self.cart.clear()


  #def receipt(self):

available_cars = [
    {
        "id": 1,
        "brand": "Toyota",
        "model": "Camry",
        "color": "White",
        "quantity": 5,
        "price": 150
    },
    {
        "id": 2,
        "brand": "Honda",
        "model": "Accord",
        "color": "Black",
        "quantity": 3,
        "price": 180
    }
]

unavailable_cars = []

renter1 = Rental(
    "aleen123",
    "1234",
    "Aleen",
    "aleen@email.com",
    22,
    "123456789"
)

renter1.add_to_cart(available_cars[0], 3)

print(renter1.cart)

